### ISSUE TITLE
[update] SVGのフルードイメージの詳細度を低くする

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/styleguide#21]
`img[src$=".svg"]`のように要素セレクタと属性セレクタを指定している。

`[src$=".svg"]`のように要素セレクタを指定しなくても問題がなさそう。詳細度も0,0,1,1から0,0,1,0にできる。

``` css
/* 修正前 */
img[src$=".svg"],
object[src$=".svg"] {
  max-width: 100%;
  width: 100%; /* IE対応 */
  height: auto;
}

/* 修正後 */
/* src属性値が.svgで終わる要素に適応 */
[src$=".svg"] {
  max-width: 100%;
  width: 100%; /* IE対応 */
  height: auto;
}
```

**Comment by manabuyasuda** [comment]
そもそも`<object>`要素は`src`ではなく`data`だった。

なので以下のようになる。

``` css
/* 修正後 */
img[src$=".svg"],
object[data$=".svg"] {
  max-width: 100%;
  width: 100%; /* IE対応 */
  height: auto;
}

/* 修正後 */
[src$=".svg"],
[data$=".svg"] {
  max-width: 100%;
  width: 100%; /* IE対応 */
  height: auto;
}

```
